// lib/models/reaction_model.dart
import 'package:hive/hive.dart';

part 'reaction_model.g.dart'; // This file will be generated by the build runner

@HiveType(typeId: 2) // Unique ID for the Reaction Hive object
class Reaction extends HiveObject {
  @HiveField(0)
  final String emoji;

  @HiveField(1)
  final String userId;

  @HiveField(2)
  final String userName;

  Reaction({required this.emoji, required this.userId, required this.userName});

  factory Reaction.fromJson(Map<String, dynamic> json) {
    return Reaction(
      emoji: json['emoji'] as String,
      // The user object might be nested or just an ID string
      userId: json['user'] is Map ? json['user']['_id'] : json['user'],
      userName: json['userName'] as String,
    );
  }
}
