// lib/models/user_model.dart
import 'package:hive/hive.dart';

part 'user_model.g.dart'; // This file will be generated by the build runner

@HiveType(typeId: 0) // Unique ID for this Hive object type
class User extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String fullName;

  @HiveField(2)
  final String email;

  @HiveField(3)
  final String? profilePictureUrl;

  @HiveField(4)
  final DateTime? createdAt;

  @HiveField(5)
  final DateTime? lastSeen;

  User({
    required this.id,
    required this.fullName,
    required this.email,
    this.profilePictureUrl,
    this.createdAt,
    this.lastSeen,
  });

  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      id: json['_id'] as String,
      fullName: json['fullName'] as String,
      email: json['email'] as String,
      profilePictureUrl: json['profilePictureUrl'] as String?,
      createdAt:
          json['createdAt'] != null
              ? DateTime.tryParse(json['createdAt'] as String)
              : null,
      lastSeen:
          json['lastSeen'] != null
              ? DateTime.tryParse(json['lastSeen'] as String)?.toLocal()
              : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      '_id': id,
      'fullName': fullName,
      'email': email,
      'profilePictureUrl': profilePictureUrl,
      'createdAt': createdAt?.toIso8601String(),
    };
  }
}
